#pragma once

#define MATRIX_ROWS 7
#define MATRIX_COLS 12
#define VIAL_TAP_DANCE_ENABLE
#define VIAL_LOCKING_KEYCODES
#define VIAL_KEYBOARD_UID {0x56, 0xC4, 0xC8, 0x18, 0x60, 0x9F, 0x72, 0x42}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {3, 4}
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define LAYER_STATE_32BIT
